2020-11-20 12:08:58,451 INFO    MainThread:36191 [wandb_setup.py:_flush():70] setting env: {}
2020-11-20 12:08:58,451 INFO    MainThread:36191 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-20 12:08:58,451 INFO    MainThread:36191 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-20 12:08:58,451 INFO    MainThread:36191 [wandb_init.py:_log_setup():303] Logging user logs to /Users/daphnedemekas/Desktop/Imperial/IntrotoML/neural_networks_51/wandb/run-20201120_120858-uw6wtt0b/logs/debug.log
2020-11-20 12:08:58,451 INFO    MainThread:36191 [wandb_init.py:_log_setup():304] Logging internal logs to /Users/daphnedemekas/Desktop/Imperial/IntrotoML/neural_networks_51/wandb/run-20201120_120858-uw6wtt0b/logs/debug-internal.log
2020-11-20 12:08:59,730 INFO    MainThread:36191 [wandb_run.py:_console_start():1218] atexit reg
2020-11-20 12:08:59,730 INFO    MainThread:36191 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.REDIRECT
2020-11-20 12:08:59,731 INFO    MainThread:36191 [wandb_run.py:_redirect():1088] Redirecting console.
2020-11-20 12:08:59,731 INFO    MainThread:36191 [redirect.py:install():204] install start
2020-11-20 12:08:59,732 INFO    MainThread:36191 [redirect.py:install():219] install stop
2020-11-20 12:08:59,732 INFO    MainThread:36191 [redirect.py:install():204] install start
2020-11-20 12:08:59,732 INFO    MainThread:36191 [redirect.py:install():219] install stop
2020-11-20 12:08:59,733 INFO    MainThread:36191 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-20 12:08:59,793 INFO    MainThread:36191 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 1
2020-11-20 12:08:59,793 INFO    MainThread:36191 [wandb_run.py:_restore():1160] restore
2020-11-20 12:08:59,794 INFO    MainThread:36191 [redirect.py:uninstall():223] uninstall start
2020-11-20 12:08:59,794 INFO    MainThread:36191 [redirect.py:_stop():278] _stop: stdout
2020-11-20 12:08:59,794 INFO    MainThread:36191 [redirect.py:_stop():284] _stop closed: stdout
2020-11-20 12:08:59,794 INFO    stdout    :36191 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-11-20 12:08:59,794 INFO    stdout    :36191 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:_stop():290] _stop joined: stdout
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:_stop():292] _stop rd closed: stdout
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:uninstall():227] uninstall done
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:uninstall():223] uninstall start
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:_stop():278] _stop: stderr
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:_stop():284] _stop closed: stderr
2020-11-20 12:08:59,795 INFO    stderr    :36191 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-11-20 12:08:59,795 INFO    stderr    :36191 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:_stop():290] _stop joined: stderr
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:_stop():292] _stop rd closed: stderr
2020-11-20 12:08:59,795 INFO    MainThread:36191 [redirect.py:uninstall():227] uninstall done
2020-11-20 12:08:59,976 INFO    MainThread:36191 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "286513d6da9c42b38479f0f0e4fdc6d2"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 809
    }
  }
}

2020-11-20 12:09:01,983 INFO    MainThread:36191 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "d03697dd7d604253b1006d58c9c1afe5"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3733
      total_bytes: 3733
    }
  }
}

2020-11-20 12:09:03,060 INFO    MainThread:36191 [wandb_run.py:_show_files():1517] logging synced files
2020-11-20 12:09:03,060 INFO    MainThread:36191 [internal.py:handle_exit():138] Internal process exited
