2020-11-20 12:12:38,690 INFO    MainThread:36543 [wandb_setup.py:_flush():70] setting env: {}
2020-11-20 12:12:38,691 INFO    MainThread:36543 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-20 12:12:38,691 INFO    MainThread:36543 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-20 12:12:38,691 INFO    MainThread:36543 [wandb_init.py:_log_setup():303] Logging user logs to /Users/daphnedemekas/Desktop/Imperial/IntrotoML/neural_networks_51/wandb/run-20201120_121238-2qu5wp1n/logs/debug.log
2020-11-20 12:12:38,691 INFO    MainThread:36543 [wandb_init.py:_log_setup():304] Logging internal logs to /Users/daphnedemekas/Desktop/Imperial/IntrotoML/neural_networks_51/wandb/run-20201120_121238-2qu5wp1n/logs/debug-internal.log
2020-11-20 12:12:39,901 INFO    MainThread:36543 [wandb_run.py:_console_start():1218] atexit reg
2020-11-20 12:12:39,901 INFO    MainThread:36543 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.REDIRECT
2020-11-20 12:12:39,902 INFO    MainThread:36543 [wandb_run.py:_redirect():1088] Redirecting console.
2020-11-20 12:12:39,902 INFO    MainThread:36543 [redirect.py:install():204] install start
2020-11-20 12:12:39,903 INFO    MainThread:36543 [redirect.py:install():219] install stop
2020-11-20 12:12:39,903 INFO    MainThread:36543 [redirect.py:install():204] install start
2020-11-20 12:12:39,906 INFO    MainThread:36543 [redirect.py:install():219] install stop
2020-11-20 12:12:39,906 INFO    MainThread:36543 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-20 12:12:39,994 INFO    MainThread:36543 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 1
2020-11-20 12:12:39,994 INFO    MainThread:36543 [wandb_run.py:_restore():1160] restore
2020-11-20 12:12:39,994 INFO    MainThread:36543 [redirect.py:uninstall():223] uninstall start
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:_stop():278] _stop: stdout
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:_stop():284] _stop closed: stdout
2020-11-20 12:12:39,995 INFO    stdout    :36543 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-11-20 12:12:39,995 INFO    stdout    :36543 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:_stop():290] _stop joined: stdout
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:_stop():292] _stop rd closed: stdout
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:uninstall():227] uninstall done
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:uninstall():223] uninstall start
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:_stop():278] _stop: stderr
2020-11-20 12:12:39,995 INFO    MainThread:36543 [redirect.py:_stop():284] _stop closed: stderr
2020-11-20 12:12:39,995 INFO    stderr    :36543 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-11-20 12:12:39,996 INFO    stderr    :36543 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-11-20 12:12:39,996 INFO    MainThread:36543 [redirect.py:_stop():290] _stop joined: stderr
2020-11-20 12:12:39,996 INFO    MainThread:36543 [redirect.py:_stop():292] _stop rd closed: stderr
2020-11-20 12:12:39,996 INFO    MainThread:36543 [redirect.py:uninstall():227] uninstall done
2020-11-20 12:12:40,135 INFO    MainThread:36543 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "2a9915903c2c4c7091425a866f4f59e0"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 809
    }
  }
}

2020-11-20 12:12:42,138 INFO    MainThread:36543 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "b344c68df08c45e48be0470105bdbb68"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4115
      total_bytes: 4115
    }
  }
}

2020-11-20 12:12:43,217 INFO    MainThread:36543 [wandb_run.py:_show_files():1517] logging synced files
2020-11-20 12:12:43,217 INFO    MainThread:36543 [internal.py:handle_exit():138] Internal process exited
